language: rust
rust:
  - 1.28.0
  - 1.32.0
script:
  - cargo build --verbose --release
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+$/
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true